version: '3.4'

services:
  tracker.pixel.service:
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    depends_on:
    - kafka

  tracker.storage.worker:
    env_file:
      - .env
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    depends_on:
    - kafka

  #infra
  zookeeper:
     image: confluentinc/cp-zookeeper:7.3.2
     container_name: zookeeper
     ports:
       - 2181:2181
     environment:
       ZOOKEEPER_CLIENT_PORT: 2181
     healthcheck:
       test: nc -z localhost 2181 || exit -1
       interval: 10s
       timeout: 10s
       retries: 3
       start_period: 5s
  
  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INNER://kafka:29092,OUTER://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INNER:PLAINTEXT,OUTER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INNER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: nc -vz kafka 29092 || exit -1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s
    links:
      - zookeeper
    depends_on:
      zookeeper:
        condition: service_healthy

  kafka-init-topics:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka-init-topics
    depends_on:
      - kafka
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
               cub kafka-ready -b kafka:29092 1 30 && \          
               kafka-topics --create --bootstrap-server kafka:29092 --replication-factor 1 --partitions 3 --topic user-events'"

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8092:8080"
    restart: always
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
